spring:
  application:
    name: netflix-zuul-api-gateway-server
server:
  port: 8765
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ribbon:
  eureka:
    enabled: false

currency-exchange-service:
  ribbon:
    listOfServers: http://localhost:8000


zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
  routes:
    currency-exchange-service:
      path: /currency-exchange-service/**
      serviceId: currency-exchange-service